# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        aws.storage:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(STACKHERO_MINIO_BUCKET)%'

