vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        uploaded_images:
            uri_prefix: '/mes-collections'
            upload_destination: aws.storage
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
#            inject_on_load: false
#            delete_on_update: true
#            delete_on_remove: true

