vich_uploader:
    db_driver: orm

    mappings:
        uploaded_images:
            uri_prefix: '%uploaded_images%'
            upload_destination: '%kernel.project_dir%/public/uploads/images/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true

